# Generated by Django 6.0.3 on 2026-03-26 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("personnel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Full official name of the training programme",
                        max_length=200,
                        unique=True,
                        verbose_name="Training Name",
                    ),
                ),
                (
                    "training_type",
                    models.CharField(
                        choices=[
                            ("BASIC", "Basic / Foundation"),
                            ("ADVANCED", "Advanced"),
                            ("SPECIALIZED", "Specialised Skill"),
                            ("REFRESHER", "Refresher / Mock Drill"),
                        ],
                        default="BASIC",
                        max_length=12,
                        verbose_name="Training Type",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
            ],
            options={
                "verbose_name": "Training Programme",
                "verbose_name_plural": "Training Programmes",
                "ordering": ["training_type", "name"],
            },
        ),
        migrations.CreateModel(
            name="TrainingInstance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "batch_no",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Batch / Certificate Prefix",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Venue / Location",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(blank=True, null=True, verbose_name="Start Date"),
                ),
                (
                    "end_date",
                    models.DateField(blank=True, null=True, verbose_name="End Date"),
                ),
                (
                    "instructor",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Instructor",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instances",
                        to="training.training",
                        verbose_name="Training Programme",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Leave blank if inter-district",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_instances",
                        to="personnel.unit",
                        verbose_name="Organising Unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Training Instance / Batch",
                "verbose_name_plural": "Training Instances / Batches",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="TrainingAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "certificate_no",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Certificate Number",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "enrolled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="enrollments_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Enrolled By",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_attendances",
                        to="personnel.volunteer",
                        verbose_name="Volunteer",
                    ),
                ),
                (
                    "training_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendances",
                        to="training.traininginstance",
                        verbose_name="Training Instance",
                    ),
                ),
            ],
            options={
                "verbose_name": "Training Attendance",
                "verbose_name_plural": "Training Attendances",
                "ordering": ["-training_instance__start_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("volunteer", "training_instance"),
                        name="unique_attendance_per_instance",
                    )
                ],
            },
        ),
    ]
