# Generated by Django 6.0.3 on 2026-03-26 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Official district / unit name (e.g. ALIPURDUAR)",
                        max_length=120,
                        unique=True,
                        verbose_name="Unit Name",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Auto-generated URL-safe identifier (e.g. alipurduar)",
                        max_length=60,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, default="", verbose_name="Description"
                    ),
                ),
            ],
            options={
                "verbose_name": "Unit",
                "verbose_name_plural": "Units",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Volunteer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "serial_no",
                    models.CharField(
                        help_text="Serial number within the unit register",
                        max_length=20,
                        verbose_name="Serial No.",
                    ),
                ),
                (
                    "block",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=120,
                        verbose_name="Block / Area",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Full Name")),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("M", "Male"),
                            ("F", "Female"),
                            ("O", "Other / Not Specified"),
                        ],
                        default="O",
                        max_length=1,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("GEN", "General"),
                            ("SC", "Scheduled Caste"),
                            ("ST", "Scheduled Tribe"),
                            ("OBC-A", "OBC-A"),
                            ("OBC-B", "OBC-B"),
                            ("OTHER", "Other"),
                        ],
                        default="GEN",
                        max_length=6,
                        verbose_name="Social Category",
                    ),
                ),
                (
                    "blood_group",
                    models.CharField(
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                            ("UNK", "Unknown"),
                        ],
                        default="UNK",
                        max_length=4,
                        verbose_name="Blood Group",
                    ),
                ),
                (
                    "dob",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Birth"
                    ),
                ),
                (
                    "date_60",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date of Attaining 60 Years"
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=30,
                        verbose_name="Mobile / Phone No.",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, default="", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "guardian_address",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Guardian Name, Contact & Permanent Address",
                    ),
                ),
                (
                    "aadhar_no",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Aadhaar Card No.",
                    ),
                ),
                (
                    "hrms_id",
                    models.CharField(
                        blank=True, default="", max_length=30, verbose_name="HRMS ID"
                    ),
                ),
                (
                    "swasthya_sathi",
                    models.BooleanField(
                        default=False, verbose_name="Enrolled in Swasthya Sathi Scheme"
                    ),
                ),
                (
                    "qualification",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Academic Qualification",
                    ),
                ),
                (
                    "computer_knowledge",
                    models.BooleanField(
                        default=False, verbose_name="Has Computer Knowledge"
                    ),
                ),
                (
                    "bank_details",
                    models.TextField(
                        blank=True, default="", verbose_name="Bank Account Details"
                    ),
                ),
                (
                    "registration_date",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date of Registration as CD Volunteer",
                    ),
                ),
                (
                    "basic_training_details",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Basic Training Details (Raw)",
                    ),
                ),
                (
                    "special_training_details",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Special Training Details (Raw)",
                    ),
                ),
                (
                    "extra_activities",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="Extra Curricular Activities",
                    ),
                ),
                (
                    "documents_ref",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Documents Reference",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to deactivate without deleting the record",
                        verbose_name="Is Active",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="volunteers",
                        to="personnel.unit",
                        verbose_name="Unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volunteer",
                "verbose_name_plural": "Volunteers",
                "ordering": ["unit", "serial_no"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("unit", "serial_no"),
                        name="unique_volunteer_serial_per_unit",
                    )
                ],
            },
        ),
    ]
