# Generated by Django 6.0.3 on 2026-03-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volunteer",
            name="aadhar_no",
            field=models.CharField(
                blank=True, default="", max_length=30, verbose_name="Aadhaar Card No."
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="block",
            field=models.CharField(
                blank=True, default="", max_length=500, verbose_name="Block / Area"
            ),
        ),
        migrations.AlterField(
            model_name="volunteer",
            name="mobile",
            field=models.CharField(
                blank=True, default="", max_length=60, verbose_name="Mobile / Phone No."
            ),
        ),
    ]
