# Generated by Django 6.0.3 on 2026-03-28 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0002_fix_field_lengths"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficeDutyPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(verbose_name="Duty Started At")),
                (
                    "ended_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Duty Ended At"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_office_duty_periods",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recorded By",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="office_duty_periods",
                        to="personnel.volunteer",
                        verbose_name="Volunteer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Office Duty Period",
                "verbose_name_plural": "Office Duty Periods",
                "ordering": ["-started_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("ended_at__isnull", True)),
                        fields=("volunteer",),
                        name="unique_open_office_duty_per_volunteer",
                    )
                ],
            },
        ),
    ]
