# Generated by Django 6.0.3 on 2026-04-08 08:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0003_office_duty_period"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OfficeDutyMonthSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveSmallIntegerField(verbose_name="Year")),
                ("month", models.PositiveSmallIntegerField(verbose_name="Month")),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="office_duty_month_submissions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Submitted By",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="office_duty_month_submissions",
                        to="personnel.unit",
                        verbose_name="Unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Office duty month submission",
                "verbose_name_plural": "Office duty month submissions",
                "ordering": ["-year", "-month", "unit__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("unit", "year", "month"),
                        name="unique_unit_office_duty_month_submission",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("month__gte", 1), ("month__lte", 12)),
                        name="office_duty_submission_month_range",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="VolunteerOfficeDutyMonth",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("year", models.PositiveSmallIntegerField(verbose_name="Year")),
                ("month", models.PositiveSmallIntegerField(verbose_name="Month")),
                (
                    "days_worked",
                    models.PositiveSmallIntegerField(
                        verbose_name="Days worked in office"
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_office_duty_months",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Recorded By",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="office_duty_months",
                        to="personnel.volunteer",
                        verbose_name="Volunteer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Volunteer office duty (monthly)",
                "verbose_name_plural": "Volunteer office duty (monthly)",
                "ordering": ["-year", "-month", "volunteer__name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("volunteer", "year", "month"),
                        name="unique_volunteer_office_duty_month",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("month__gte", 1), ("month__lte", 12)),
                        name="office_duty_month_month_range",
                    ),
                ],
            },
        ),
    ]
