# Generated by Django 6.0.3 on 2026-04-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0004_office_duty_monthly_csv"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="deroster_reason",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Why this volunteer was de-rostered from service.",
                verbose_name="De-roster reason",
            ),
        ),
        migrations.AddField(
            model_name="volunteer",
            name="derostered_on",
            field=models.DateField(
                blank=True,
                help_text="Date removed from active roster (if de-rostered).",
                null=True,
                verbose_name="De-rostered on",
            ),
        ),
    ]
