# Generated by Django 6.0.3 on 2026-04-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0005_volunteer_deroster_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="volunteer",
            name="exceptional_performance",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Running log of notable achievements, commendations, and good work citations.",
                verbose_name="Exceptional Performance",
            ),
        ),
    ]
