# Generated by Django 6.0.3 on 2026-04-23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0006_volunteer_exceptional_performance"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OfficeDutyPeriod",
        ),
    ]
