# Generated by Django 6.0.3 on 2026-03-26 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("incidents", "0001_initial"),
        ("personnel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name, e.g. 'Life Jacket (Adult)'",
                        max_length=200,
                        verbose_name="Equipment Name",
                    ),
                ),
                (
                    "unique_id",
                    models.CharField(
                        help_text="Departmental asset tag or serial number",
                        max_length=100,
                        unique=True,
                        verbose_name="Unique ID / Asset Tag",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("FIRE", "Fire Fighting"),
                            ("RESCUE", "Search & Rescue"),
                            ("MED", "Medical / First Aid"),
                            ("COMM", "Communication"),
                            ("FLOOD", "Flood Relief"),
                            ("PPE", "Personal Protective Equipment"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=8,
                        verbose_name="Category",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Number of units of this equipment item",
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OK", "Functional"),
                            ("REPAIR", "Under Repair"),
                            ("DISPOSED", "Disposed / Written Off"),
                        ],
                        default="OK",
                        max_length=8,
                        verbose_name="Status",
                    ),
                ),
                (
                    "last_check_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last Inspection Date"
                    ),
                ),
                (
                    "next_due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Next Inspection Due"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="equipment_items",
                        to="personnel.unit",
                        verbose_name="Assigned Unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment",
                "verbose_name_plural": "Equipment Items",
                "ordering": ["unit", "category", "name"],
            },
        ),
        migrations.CreateModel(
            name="EquipmentMaintenanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "check_date",
                    models.DateField(verbose_name="Inspection / Service Date"),
                ),
                (
                    "status_after_check",
                    models.CharField(
                        choices=[
                            ("OK", "Functional"),
                            ("REPAIR", "Under Repair"),
                            ("DISPOSED", "Disposed / Written Off"),
                        ],
                        default="OK",
                        max_length=8,
                        verbose_name="Status After Check",
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Observations, repairs done, parts replaced, etc.",
                        verbose_name="Remarks",
                    ),
                ),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Checked By",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_logs",
                        to="equipment.equipment",
                        verbose_name="Equipment",
                    ),
                ),
            ],
            options={
                "verbose_name": "Equipment Maintenance Log",
                "verbose_name_plural": "Equipment Maintenance Logs",
                "ordering": ["-check_date"],
            },
        ),
        migrations.CreateModel(
            name="IncidentEquipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity_deployed",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Quantity Deployed"
                    ),
                ),
                (
                    "returned",
                    models.BooleanField(default=False, verbose_name="Returned"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incident_allocations",
                        to="equipment.equipment",
                        verbose_name="Equipment",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_allocations",
                        to="incidents.incident",
                        verbose_name="Incident",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident Equipment Allocation",
                "verbose_name_plural": "Incident Equipment Allocations",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("incident", "equipment"),
                        name="unique_equipment_per_incident",
                    )
                ],
            },
        ),
    ]
