# Generated by Django 6.0.3 on 2026-04-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("equipment", "0004_equipmenttype_and_fk"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipment",
            name="equipment_maintainance_note",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Reminder notes on what to do during maintenance checks.",
                verbose_name="Equipment Maintainance Note",
            ),
        ),
        migrations.AddField(
            model_name="equipmenttype",
            name="picture",
            field=models.ImageField(
                blank=True,
                help_text="Reference picture for this equipment type.",
                null=True,
                upload_to="equipment/types/",
                verbose_name="Picture",
            ),
        ),
    ]
