# Generated by Django 6.0.3 on 2026-03-26 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("incidents", "0001_initial"),
        ("personnel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("AMBULANCE", "Ambulance"),
                            ("FIRE", "Fire Truck"),
                            ("JEEP", "Jeep / SUV"),
                            ("MINIBUS", "Mini Bus"),
                            ("MOTO", "Motorcycle"),
                            ("BOAT", "Rescue Boat"),
                            ("TRUCK", "Truck / Lorry"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=10,
                        verbose_name="Vehicle Type",
                    ),
                ),
                (
                    "registration_no",
                    models.CharField(
                        help_text="Government registration plate, e.g. WB 75 AB 1234",
                        max_length=20,
                        unique=True,
                        verbose_name="Registration Number",
                    ),
                ),
                (
                    "capacity",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Passenger seats or load capacity in kg",
                        verbose_name="Capacity",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("DEPLOYED", "Deployed / In Use"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("DISPOSED", "Disposed / Written Off"),
                        ],
                        default="AVAILABLE",
                        max_length=12,
                        verbose_name="Status",
                    ),
                ),
                (
                    "last_service_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Last Service Date"
                    ),
                ),
                (
                    "next_service_due",
                    models.DateField(
                        blank=True, null=True, verbose_name="Next Service Due"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="personnel.unit",
                        verbose_name="Assigned Unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle",
                "verbose_name_plural": "Vehicles",
                "ordering": ["unit", "vehicle_type", "registration_no"],
            },
        ),
        migrations.CreateModel(
            name="VehicleMaintenanceLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "service_date",
                    models.DateField(verbose_name="Service / Inspection Date"),
                ),
                (
                    "status_after_service",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("DEPLOYED", "Deployed / In Use"),
                            ("MAINTENANCE", "Under Maintenance"),
                            ("DISPOSED", "Disposed / Written Off"),
                        ],
                        default="AVAILABLE",
                        max_length=12,
                        verbose_name="Status After Service",
                    ),
                ),
                (
                    "odometer_km",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Odometer Reading (km)"
                    ),
                ),
                (
                    "remarks",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Work done, parts replaced, issues found, etc.",
                        verbose_name="Remarks",
                    ),
                ),
                (
                    "serviced_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Logged By",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_logs",
                        to="fleet.vehicle",
                        verbose_name="Vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vehicle Maintenance Log",
                "verbose_name_plural": "Vehicle Maintenance Logs",
                "ordering": ["-service_date"],
            },
        ),
        migrations.CreateModel(
            name="IncidentVehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "dispatched_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Dispatched At"
                    ),
                ),
                (
                    "returned_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Returned At"
                    ),
                ),
                (
                    "driver_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=200,
                        verbose_name="Driver Name",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "authorised_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Authorised By",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_allocations",
                        to="incidents.incident",
                        verbose_name="Incident",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incident_allocations",
                        to="fleet.vehicle",
                        verbose_name="Vehicle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident Vehicle Allocation",
                "verbose_name_plural": "Incident Vehicle Allocations",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("incident", "vehicle"),
                        name="unique_vehicle_per_incident",
                    )
                ],
            },
        ),
    ]
