# Generated by Django 6.0.3 on 2026-03-26 07:56

import civil_defence_app.incidents.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("personnel", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Short descriptive title, e.g. 'Flash flood in Alipurduar Block I'",
                        max_length=255,
                        verbose_name="Incident Title",
                    ),
                ),
                (
                    "incident_type",
                    models.CharField(
                        choices=[
                            ("FLOOD", "Flood"),
                            ("FIRE", "Fire"),
                            ("COLLAPSE", "Building / Structure Collapse"),
                            ("STORM", "Storm / Cyclone"),
                            ("ACCIDENT", "Road / Rail Accident"),
                            ("DROUGHT", "Drought"),
                            ("EPIDEMIC", "Epidemic / Disease Outbreak"),
                            ("SEARCH", "Search & Rescue"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=12,
                        verbose_name="Incident Type",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Diary"),
                            ("OPEN", "Open / Active Response"),
                            ("CLOSED", "Closed / Completed"),
                        ],
                        default="OPEN",
                        max_length=8,
                        verbose_name="Status",
                    ),
                ),
                (
                    "location_text",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Free-text: village, block, PS, landmark",
                        max_length=500,
                        verbose_name="Location Description",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Incident Start Time"
                    ),
                ),
                (
                    "end_time",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Incident End Time"
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Full narrative: what happened, scope, damage assessment",
                        verbose_name="Incident Description",
                    ),
                ),
                (
                    "final_report",
                    models.TextField(
                        blank=True, default="", verbose_name="Final Incident Report"
                    ),
                ),
                (
                    "reported_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_incidents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Reported By",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incidents",
                        to="personnel.unit",
                        verbose_name="Handling Unit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident",
                "verbose_name_plural": "Incidents",
                "ordering": ["-start_time", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IncidentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("timestamp", models.DateTimeField(verbose_name="Timestamp")),
                (
                    "action_taken",
                    models.TextField(
                        help_text="What was done at this point in the response",
                        verbose_name="Action Taken",
                    ),
                ),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Entered By",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_entries",
                        to="incidents.incident",
                        verbose_name="Incident",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident Log Entry",
                "verbose_name_plural": "Incident Log Entries",
                "ordering": ["timestamp"],
            },
        ),
        migrations.CreateModel(
            name="IncidentMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.FileField(
                        help_text="Photo (jpg/png) or video (mp4) file",
                        upload_to=civil_defence_app.incidents.models.incident_media_path,
                        verbose_name="File",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Caption"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, default="", max_length=200, verbose_name="Tags"
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="incidents.incident",
                        verbose_name="Incident",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Uploaded By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident Media",
                "verbose_name_plural": "Incident Media Files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IncidentAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="e.g. Team Leader, First Aider, Driver …",
                        max_length=100,
                        verbose_name="Role in Incident",
                    ),
                ),
                (
                    "assigned_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Assigned At"),
                ),
                (
                    "notes",
                    models.TextField(blank=True, default="", verbose_name="Notes"),
                ),
                (
                    "assigned_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Assigned By",
                    ),
                ),
                (
                    "incident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="incidents.incident",
                        verbose_name="Incident",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incident_assignments",
                        to="personnel.volunteer",
                        verbose_name="Volunteer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incident Assignment",
                "verbose_name_plural": "Incident Assignments",
                "ordering": ["-assigned_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("incident", "volunteer"),
                        name="unique_volunteer_per_incident",
                    )
                ],
            },
        ),
    ]
