# Generated by Django 6.0.3 on 2026-03-27 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="incident_number",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated: UNIT-YEAR-NNN  (e.g. ALIPURDUAR-2026-003)",
                max_length=40,
                null=True,
                unique=True,
                verbose_name="Incident Number",
            ),
        ),
    ]
