# Generated by Django 6.0.3 on 2026-04-08 11:28

from django.db import migrations, models

_VALID_ROLES = frozenset({"SCUBA_DIVER", "DRIVER", "FIREFIGHTER", "CUTTER"})


def normalize_assignment_roles(apps, schema_editor):
    """Map legacy free-text or empty role values to a valid choice before AlterField."""
    IncidentAssignment = apps.get_model("incidents", "IncidentAssignment")
    for row in IncidentAssignment.objects.iterator():
        if row.role not in _VALID_ROLES:
            row.role = "FIREFIGHTER"
            row.save(update_fields=["role"])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0002_incident_incident_number"),
    ]

    operations = [
        migrations.RunPython(normalize_assignment_roles, noop_reverse),
        migrations.AlterField(
            model_name="incidentassignment",
            name="role",
            field=models.CharField(
                choices=[
                    ("SCUBA_DIVER", "Scuba Diver"),
                    ("DRIVER", "Driver"),
                    ("FIREFIGHTER", "Fire-fighter"),
                    ("CUTTER", "Cutter"),
                ],
                default="FIREFIGHTER",
                help_text="Role this volunteer fills on this incident.",
                max_length=32,
                verbose_name="Role in Incident",
            ),
        ),
    ]
