# Generated by Django 6.0.3 on 2026-03-27 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("personnel", "0002_fix_field_lengths"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("UNIT_IN_CHARGE", "Unit In-Charge"),
                    ("VOLUNTEER", "Volunteer"),
                ],
                default="VOLUNTEER",
                help_text="Determines what the user can see and do in the system.",
                max_length=16,
                verbose_name="Role",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                help_text="The district unit this user manages / belongs to. Required for Unit In-Charge accounts.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_accounts",
                to="personnel.unit",
                verbose_name="Assigned Unit",
            ),
        ),
    ]
