# Generated by Django 6.0.3 on 2026-03-29 14:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_role_user_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="rank",
            field=models.CharField(blank=True, max_length=128, verbose_name="Rank"),
        ),
        migrations.AddField(
            model_name="user",
            name="telephone",
            field=models.CharField(
                blank=True,
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Enter exactly 10 digits (no spaces or dashes).",
                        regex="^\\d{10}$",
                    )
                ],
                verbose_name="Telephone",
            ),
        ),
    ]
